version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: persona-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: persona_chatbot
      POSTGRES_USER: persona_user
      POSTGRES_PASSWORD: persona_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - persona-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U persona_user -d persona_chatbot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: persona-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: persona_chatbot
      DB_USER: persona_user
      DB_PASSWORD: persona_password
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET:-super_secret_jwt_key_for_production_change_this}
      JWT_EXPIRE: 15m
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-super_secret_refresh_jwt_key_for_production_change_this}
      JWT_REFRESH_EXPIRE: 7d
      
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      # Logging Configuration
      LOG_LEVEL: info
      
      # CORS Configuration
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./server/logs:/app/logs
    networks:
      - persona-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: persona-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    networks:
      - persona-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  persona-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local