[variables]
NIXPACKS_NODE_VERSION = "18"

[phases.setup]
nixPkgs = ['nodejs', 'npm']
cmds = ['cd server']

[phases.install]
cmds = ['cd server && npm ci']

[phases.build]
cmds = ['echo "No build step required for Node.js server"']

[start]
cmd = 'cd server && npm start'